# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0 # pause dependabot
    commit-message:
      prefix: 'chore: '
    ignore:
      # exifreader@4.20.0 seems to have introduced a regression: with it we
      # can't read XMP metadata out of a PNG file.
      - dependency-name: 'exifreader'

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - '*'
